### ISSUE TITLE
親クラスのインスタンスはアソシエーションメソッドを使い生成する

### ISSUE THREAD

**Issue by norotime** [masarusan24/achieve#1]
https://github.com/masarusan24/achieve/blob/3135e0a1d0a80f2ba1ca0da96d735a42732c0152/app/controllers/blogs_controller.rb#L14

参考：

```
collection.buildメソッドは、関連付けが行われたオブジェクトを1つまたは複数返します。返されるオブジェクトは、渡された属性に基いてインスタンス化され、外部キーを経由するリンクが作成されます。関連付けられたオブジェクトは、値が返された時点ではまだ保存されていないことにご注意ください。
```

https://railsguides.jp/association_basics.html#has-many%E3%81%A7%E8%BF%BD%E5%8A%A0%E3%81%95%E3%82%8C%E3%82%8B%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89-collection-build-attributes

**Comment by norotime** [comment]
@masarusan24 他にもないか探して修正してくださいねーー。

**Comment by masarusan24** [comment]
@norotime ざっと探してみて、書き換えられそうな`blogs_controller`内の記述を全て見直して修正しました。

このように書き換えるメリットって、以下の１行を減らしてより直感的な記述が可能になるというところでしょうか？

`@blog.user_id = current_user.id `

**Comment by norotime** [comment]
はい。その通りです！
