### ISSUE TITLE
READMEにアプリケーションの仕様や環境情報を記述する

### ISSUE THREAD

**Issue by norotime** [masarusan24/achieve#10]
https://github.com/masarusan24/achieve/blob/master/README.md

@masarusan24 READMEはソースコードの顔です。チャレンジしてみましょう！

**Comment by masarusan24** [comment]
@norotime いろんな所からパクって書いてみました。
とりあえずこんな感じでいかがでしょう？

**Comment by norotime** [comment]
@masarusan24 いいですね！笑　ひとまずはそんな感じで！
