### ISSUE TITLE
Gemfileはデフォルトコメントを削除して見通しをよくし、利用目的や環境ごとに空行で区切る

### ISSUE THREAD

**Issue by norotime** [masarusan24/achieve#11]
https://github.com/masarusan24/achieve/blob/e741deef530631afef53b83f44090e75958fefd6/Gemfile#L9

**Comment by masarusan24** [comment]
@norotime デフォルトコメントは消しましたが、自分で入れたコメントは備忘録のために残してあります。(本当はこれもわかり切ってる場合は消した方がいいんでしょうけど)

**Comment by norotime** [comment]
@masarusan24 わかりました〜
