### ISSUE TITLE
【挑戦★★★】Slim を導入する

### ISSUE THREAD

**Issue by norotime** [masarusan24/achieve#12]
https://github.com/masarusan24/achieve/blob/e741deef530631afef53b83f44090e75958fefd6/app/views/users/_form.html.erb#L1

@masarusan24 現場では、テンプレートエンジンとして使われることが多いです。コード記述量も半減します。ぜひ、慣れてきたらチャレンジしてみてください。

**Comment by norotime** [comment]
@masarusan24 https://github.com/slim-template/slim/blob/master/README.jp.md

**Comment by masarusan24** [comment]
@norotime [erb2slim](https://github.com/slim-template/html2slim)を使ってちょとズルしてしまいましたが、Slim導入してみました。
(とはいえ、単純にerb->slim変換したのみでは使えず、インデント調整等で少々ハマりましたが。。)

ただ、ブログ一覧画面のボタン間の余白調整がまだうまく行ってないので本番反映はしておらず、GitHubにも[erb2slim](https://github.com/masarusan24/achieve/tree/erb2slim)ブランチの方にプッシュしています。

HTMLは変わっていないように見えますし、CSSも特にいじっていないのですが、Slimの仕様ってことではないですよね…

![achieve 2018-02-22 13-29-36](https://user-images.githubusercontent.com/17737460/36520661-84009f8c-17d5-11e8-929e-c012d58f1221.png)

![achieve 2018-02-22 13-31-28](https://user-images.githubusercontent.com/17737460/36520660-83dd0194-17d5-11e8-9734-56b3282f377f.png)

**Comment by norotime** [comment]
@masarusan24 うーーーん。何だろう？初めて見聞きしました。

**Comment by norotime** [comment]
@masarusan24 Haml と Slimの仕様の違いで発生する、ようなブログ記事はありましたね。ライブラリの中身を見ていないので断言ができませんが、HTMLのソースに空白の違いはありますか？
見た目ではなく、生成結果レベルで確認したいです。

**Comment by masarusan24** [comment]
@norotime ブログひとつの投稿分のHTMLソースは以下のような感じです。
いずれも「ページのソースを表示」からコピペしたものです。

## 本番環境(erb)
```
<div class="col-xs-12 col-md-6 blog-panel">
   <h2>etest</h2>
   <p>test</p>
   <p>投稿者:kiseki</p>
   <p>作成日時:2018-02-10 04:09:01 UTC</p>
   <div class="blog-link">
   <a class="btn btn-default" href="/blogs/17?locale=ja">詳細画面へ</a>
   <a class="btn btn-info" disabled="disabled" href="">編集画面へ</a>
   <a class="btn btn-danger" disabled="disabled" href="">削除する</a>
   </div>
</div>
```

## ローカル開発環境(slim)
```
<div class="col-xs-12 col-md-6 blog-panel"><h2>title with image</h2><p>content with image 111</p><p>投稿者:ito</p><p>作成日時:2018-02-21 08:06:05 UTC</p><div class="blog-link"><a class="btn btn-default" href="/blogs/72?locale=ja">詳細画面へ</a><a class="btn btn-info" href="/blogs/72/edit?locale=ja">編集画面へ</a><a data-confirm="削除しますか？" class="btn btn-danger" rel="nofollow" data-method="delete" href="/blogs/72?locale=ja">削除する</a></div></div>
```

slimで生成された方は、改行が反映されてないですね。
ただ、そのくらいしか違いが見当たらないです。

> Haml と Slimの仕様の違いで発生する、ようなブログ記事はありましたね。

こちらはどの記事でしょうか？
私も探してみましたがズバリな記事は見つからず。。

**Comment by masarusan24** [comment]
slim導入自体は終わっているのでクローズします。
