### ISSUE TITLE
文字列よりもシンボルの方が高速処理されるためシンボル表記に統一する

### ISSUE THREAD

**Issue by norotime** [masarusan24/achieve#2]
https://github.com/masarusan24/achieve/blob/3135e0a1d0a80f2ba1ca0da96d735a42732c0152/app/controllers/blogs_controller.rb#L20

参考：

```
シンボルを使うメリットは

新しく文字列を生成しない分やや効率がよく、比較も高速。
文字の意味がはっきりするのでコードが読みやすくなる
immutable なので内容を書き換えられる心配がない
```

https://docs.ruby-lang.org/ja/latest/class/Symbol.html

**Comment by norotime** [comment]
@masarusan24 他にもないか探して修正してくださいねーー。

**Comment by masarusan24** [comment]
@norotime 全`controller`を見直してシンボルに書き換えられるところを書き換えました！
文字列とシンボルの違いに関してはまだ理解が曖昧な部分があるので、今後引き続き学習していきます。

**Comment by norotime** [comment]
素晴らしい！
実務で求められることはどんなに細かいことでもレビューでお伝えしていきますねー！

**Comment by masarusan24** [comment]
> 実務で求められることはどんなに細かいことでもレビューでお伝えしていきますねー！

はい、コードレビュー文化で揉まれたことがなかったのでとてもありがたいです！
