### ISSUE TITLE
国際化のため英語（en）対応させる

### ISSUE THREAD

**Issue by norotime** [masarusan24/achieve#4]
https://github.com/masarusan24/achieve/blob/ed60fa7e09766f511c82c57177fa8932ec5f076e/app/controllers/application_controller.rb#L1

```
1つのアプリケーションで 2つ以上のロケールをサポートしたい ことも当然あるでしょう。そのような場合、リクエストとリクエストの間でロケールを設定し、受け渡す必要があります。
```

https://railsguides.jp/i18n.html#rails%E3%82%A2%E3%83%97%E3%83%AA%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%92%E5%9B%BD%E9%9A%9B%E5%8C%96%E5%90%91%E3%81%91%E3%81%AB%E8%A8%AD%E5%AE%9A%E3%81%99%E3%82%8B-%E3%83%AD%E3%82%B1%E3%83%BC%E3%83%AB%E3%81%AE%E8%A8%AD%E5%AE%9A%E3%81%A8%E5%8F%97%E3%81%91%E6%B8%A1%E3%81%97

@masarusan24 国際化対応は、Webアプリケーションの先鋭的なチャレンジと言えます。スタートアップではほぼ英語化は必須と思います。
1億しかいないガラパゴスニッポンよりも、80億いる世界展開を目指そうという動きは、よくある話です。
そのため、あまり顕在化しませんが、i18n対応できるスキルは、実は、重宝されます。
できる方には、DIVERの国際化作業もお任せしたいくらいです。

**Comment by masarusan24** [comment]
@norotime commit db8fc226941222070339b654ea03439a46365480 で、とりいそぎURL末尾に```?locale=en```を付与することで英語のバリデーションエラーメッセージが出るように対応しました。

**Comment by norotime** [comment]
@masarusan24 もうちょいやりましょう！
せめて、入力欄の title や contentなど。

**Comment by masarusan24** [comment]
@norotime commit 95bab041b194a1d73ab841e3473d5de2636c9174 で、対応範囲を広げました。
ブログ一覧、詳細画面、新規作成、お問い合わせフォームです。

ただ、ローカルでは狙い通りの英語表記になったものの、Herokuデプロイ後に中途半端な表記になってしまいましたので、DIVERで質問投稿しました。
https://diver.diveintocode.jp/questions/4056

**Comment by norotime** [comment]
@masarusan24 あともうちょいですね！
HerokuとCloud9の違いは、環境変数、使用環境（Cloud9は開発、Herokuは本番）などです。
よく確認してみましょう。

**Comment by norotime** [comment]
@masarusan24 この辺ですかねえ。
`config.i18n.fallbacks = true`
https://github.com/masarusan24/achieve/blob/master/config/environments/production.rb

**Comment by norotime** [comment]
あとは、コミットしておらず、Herokuにデプロイされていないとか。

**Comment by masarusan24** [comment]
うーん、コミットする毎に随時```git push heroku master```してるのでHerokuにデプロイされてないことはないと思うんです。
```config.i18n.fallbacks = true```
この辺りを見直してみます。

**Comment by masarusan24** [comment]
@norotime ありがとうございます。
ドンピシャでした！
```config.i18n.fallbacks = false```にすることで解決しました。

```
  # Enable locale fallbacks for I18n (makes lookups for any locale fall back to
  # the I18n.default_locale when a translation cannot be found).
```
こちらのコメントにあるように、```fallbacks = true```の時は、
en.ymlから翻訳文が見つからない場合は、検索対象をデフォルトのロケール(この場合は```ja```)に戻していたようです。

私の場合、en.ymlには最低限の訳文しか書いてなかったので、例えば「ブログ一覧」のような見出しの英訳が見つからず、デフォルトである日本語の見出しが表示されていた…ということだと思われます。

```fallbacks = false```とすると、en.ymlで指定がない限りはtメソッドの引数を(snake_case)->(Camel Case)に変換した文字列が表示されるため狙い通りの表記となる、と理解しました。

**Comment by masarusan24** [comment]
@norotime その後、commit a23734d239d2962a07a3fd664280ac256eef71d3 この辺りで他の部分もいろいろ英語対応してみました。
お手すきの際にご確認いただき、おかしな記述があればまたissue登録していただければと思います。

**Comment by norotime** [comment]
@masarusan24 DIVERの i18n 対応、手伝ってもらえませんか？w
