### ISSUE TITLE
SQLクエリ取得量が多すぎる場合のハングを防ぐ

### ISSUE THREAD

**Issue by norotime** [masarusan24/achieve#6]
https://github.com/masarusan24/achieve/blob/ed60fa7e09766f511c82c57177fa8932ec5f076e/app/controllers/blogs_controller.rb#L24

@masarusan24 allメソッドは極めて危険です。100万件レコードがあるかもしれません。モデル等で制御しましょう。

limit
https://railsguides.jp/active_record_querying.html#limit%E3%81%A8offset

scope
https://railsguides.jp/active_record_querying.html#%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%97

コントローラは、アクションの振り分けに注力し、モデルでデータの制御を担うと綺麗です。

**Comment by masarusan24** [comment]
@norotime モデル側で```index```スコープを設定して```limit```で上限を100件とし、コントローラ側では```index```スコープを呼び出すように変更しました。
```index```スコープは他のモデルでも使用することが想定されるため、```application_record.rb```で制御しました。

**Comment by norotime** [comment]
@masarusan24 変更できてますか？（ちょっと見当たらなかったです。）

**Comment by masarusan24** [comment]
@norotime https://github.com/masarusan24/achieve/blob/master/app/models/application_record.rb
モデル部分での制御は、こちらの以下の部分になります。

```
  MAX = 100
  scope :index, -> { limit(MAX) }
```

で、`BlogsController`のindexアクションをこのようにしています。

```
  def index
    @blogs = Blog.index
  end
```

**Comment by norotime** [comment]
@masarusan24 あーー全部のモデルに適用させたのですね。モデルによって変える必要がなければ良いですね！

**Comment by masarusan24** [comment]
@norotime 
> あーー全部のモデルに適用させたのですね。

そうですそうです。
allメソッドを使うのは危険、という考えは全てのモデルについて当てはまると思い、そのようにしました。
