### ISSUE TITLE
投稿したユーザかどうか？の判定はViewヘルパーなど外部メソッド化できないか検討する

### ISSUE THREAD

**Issue by norotime** [masarusan24/achieve#8]
https://github.com/masarusan24/achieve/blob/ed60fa7e09766f511c82c57177fa8932ec5f076e/app/controllers/blogs_controller.rb#L38

アクション内に処理が来てから返す、というのはいささか無理ヤリな感じがします。
あらかじめメソッド化しておき、アクション実行前に制御する方が良いと感じます。

少し検討してご意見を聞かせてくださいませ。

**Comment by norotime** [comment]
@masarusan24 フィルタの章を読むとヒントがわかるでしょう。
https://railsguides.jp/action_controller_overview.html#%E3%83%95%E3%82%A3%E3%83%AB%E3%82%BF

**Comment by masarusan24** [comment]
@norotime すみませんまだ検討しきれていないので、検討後、またコメントします。

**Comment by masarusan24** [comment]
@norotime 検討した結果、commit 902f523 で```before_action```で制御するようにしました。
