### ISSUE TITLE
【挑戦★★】gem banken を導入する

### ISSUE THREAD

**Issue by norotime** [masarusan24/achieve#9]
https://github.com/masarusan24/achieve/blob/902f523376b40a2ee30d145855ad4c5db48184d1/app/controllers/blogs_controller.rb#L69

@masarusan24 チャレンジです！
★：　　時間をかければできる
★★：　時間をかけて、文献を読み込めばできる
★★★：時間をかけて、文献を読み込み、検証を重ねればできる

**Comment by norotime** [comment]
![2018-02-16 23 36 24](https://user-images.githubusercontent.com/7435505/36312734-d18a910c-1372-11e8-9a61-5828b80bd56f.png)

**Comment by masarusan24** [comment]
@norotime BankenチュートリアルとGitHubのソース(特に```authorize!```メソッドのあたり)を読み込んでいます。
```authorize!```メソッドを呼び出した時点でのアクションを自動的に取ってくるようなので、before_actionで```authorize!```を呼ぶのはあまり良くないのかな…？
もう少し読み込んでみます。

**Comment by masarusan24** [comment]
@norotime commit fe72466cf1e8045a02b756a919871b42c04b01e3 と commit e741deef530631afef53b83f44090e75958fefd6 でBankenを用いた編集と削除の制御を加えてみました！
結局、before_actionで```authorize!```メソッドを呼び出しても問題なかったです。
ソース読んでみてまだ全部理解し切れてはいませんが、paramsからうまいことコントローラ名やアクション名を拾ってくるんですねぇ。
